FormCheckor.errorSource=[
	['validation-failed' , 'Validation failed.'],
	['validate-required' , 'This is a required field.'],
	['validate-number' , 'Please enter a valid number in this field.'],
	['validate-digits' , 'Please use numbers only in this field. please avoid spaces or other characters such as dots or commas.'],
	['validate-integer' , 'Please enter a valid integer in this field'],
	['validate-alpha' , 'Please use letters only (a-z) in this field.'],
	['validate-alphanum' , 'Please use only letters (a-z) or numbers (0-9) only in this field. No spaces or other characters are allowed.'],
	['validate-date' , 'Please enter a valid date.'],
	['validate-email' , 'Please enter a valid email address. For example fred@domain.com .'],
	['validate-url' , 'Please enter a valid URL.'],	
	['validate-date-au' , 'Please use this date format: dd/mm/yyyy. For example 17/03/2006 for the 17th of March, 2006.'],
	['validate-currency-dollar' , 'Please enter a valid $ amount. For example $100.00 .'],
	['validate-date-cn' , 'Please use this date format: yyyy-mm-dd. For example 2006-03-16.'],
	['validate-file' , 'Please enter file type in [%s]'],	
	['validate-pattern' , 'Validation failed.'],
	['validate-chinese','Please enter chinese'],
	['validate-ip','Please enter a valid IP address'],
	['validate-phone','Please enter a valid phone number,current length is %s.'],
	['validate-mobile-phone','Please enter a valid mobile phone,For example 13910001000.current length is %s.'],	
	['validate-zip','please enter a valid zip.'],			
	['validate-number-min' , 'min value is %s.'],
	['validate-number-max' , 'max value is %s.'],
	['validate-number-range' , 'Please enter number between %s and %s'],	
	['validate-integer-range' , 'Please enter integer value between %s and %s'],
	['validate-integer-min' , 'the min integer value is %s'],
	['validate-integer-max' , 'the max integer value is %s'],	
	['validate-length-min' , 'min length is %s,current length is %s.'],
	['validate-length-max' , 'max length is %s,current length is %s.'],
	['validate-length-range' , 'Please enter value length between %s and %s,current length is %s'],	
	['validate-lengthB-min' ,   'min length is  %s,chinese as two.'],
	['validate-lengthB-max' ,   'max length is  %s,chinese as two.'],
	['validate-lengthB-range' , 'Please enter value byte length between %s and %s,chinese take two bytes.'],	
	['validate-elm-equals','Conflicting with above value.'],
	['validate-elm-number-lessthan','Input value must be less than above value.'],
	['validate-elm-number-greatthan','Input value must be great than above value.'],
	['validate-radio-checkbox-one-required' , 'Please select one of the above options.'],
	['validate-checkbox-range','please choose options between %s and %s.'],		
	['validate-select-one-required','must choose as least one.'],	
	['validate-select-range','pleas select options between %s to %s.'],
	['validate-ajax',function(v,elm,args,metadata) {
		return elm.getAttribute('validateFailedMessage') || Validator.messages['validation-failed'];
	}]
];
