FormCheckor.errorSource= [
	['validation-failed' , '验证失败.'],
	['validate-required' ,        '请输入值.'],
	['validate-number' , '请输入有效的数字.'],
	['validate-digits' , '请输入一个数字. 避免输入空格],逗号,分号等字符'],
	['validate-integer' ,'请输入正确的整数'],	
	['validate-alpha' , '请输入英文字母.'],
	['validate-alphanum' , '请输入英文字母或是数字,其它字符是不允许的.'],
	['validate-date' , '请输入有效的日期.'],
	['validate-email' , '请输入有效的邮件地址,如 username@example.com.'],
	['validate-url' , '请输入有效的URL地址.'],
	['validate-date-au' , 'Please use this date format: dd/mm/yyyy. For example 17/03/2006 for the 17th of March, 2006.'],
	['validate-currency-dollar' , 'Please enter a valid $ amount. For example $100.00 .'],	
	['validate-date-cn' , '请使用这样的日期格式: yyyy-mm-dd. 例如:2006-03-17.'],
	['validate-file' , '文件类型应该为[%s]其中之一'],
	['validate-pattern' , '输入的值不匹配'],
	['validate-chinese','请输入中文'],
	['validate-ip','请输入正确的IP地址'],
	['validate-phone','请输入正确的电话号码,如:0571-81951342,当前长度为%s.'],
	['validate-mobile-phone','请输入正确的手机号码,当前长度为%s.'],
	['validate-zip','请输入正确的邮政编码'],			
	['validate-number-min' , '最小值为%s'],
	['validate-number-max' , '最大值为%s'],	
	['validate-number-range' , '输入值应该为 %s 至 %s 的数字'],
	['validate-integer-range' , '输入值应该为 %s 至 %s 的整数'],
	['validate-integer-min' , '最小值为%s'],
	['validate-integer-max' , '最大值为%s'],	
	['validate-length-min' , '最小长度为%s,当前长度为%s.'],
	['validate-length-max', '最大长度为%s,当前长度为%s.'],
	['validate-length-range' , '输入值的长度应该在 %s 至 %s 之间,当前长度为%s.'],	
	['validate-lengthB-min' ,   '最小长度为%s,中文算2个字.'],
	['validate-lengthB-max' ,   '最大长度为%s,中文算2个字.'],
	['validate-lengthB-range' , '输入值的长度应该在 %s 至 %s 之间,中文算2个字.'],		
	['validate-elm-number-lessthan','应该小于前面的值'],
	['validate-elm-number-greatthan','应该大于前面的值'],
	['validate-elm-equals','与上面不一至,请重新输入'],	
	['validate-radio-checkbox-one-required' , '在上面选项至少选择一个.'],	
	['validate-checkbox-range','请选择%s到%s个选项.'],		
	['validate-select-one-required','必选项，请选择.'],	
	['validate-select-range','请选择%s到%s个选项.'],	
	['validate-ajax',function(v,elm,args,metadata) {
		return elm.getAttribute('validateFailedMessage') || Validator.messages['validation-failed'];
	}]
];